name: Update trunk changelog and merge back to develop branch

on:
  release:
    types: [prereleased]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
          ref: ${{ github.event.release.target_commitish }}
          
      - name: Update plugin version numbers
        uses: tj-actions/sync-release-version@v11
#        id: sync-release-version
        with:
          pattern: 'version='
#          current_version: '1.0.1'  # Omit to use git tag.
#          new_version: '1.0.2'  # Omit when running on a release action.
          paths: |
            readme.txt
 #           test/subdir/README.md
 
      - name: Update plugin version numbers 2
        uses: tj-actions/sync-release-version@v11
        with:
          pattern: 'Stable tag: '
          paths: README.md
            
      - name: Commit version to trunk
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: trunk
          commit_message: Update plugin version to ${{ github.event.release.tag_name }}
          file_pattern: readme.txt README.md #package-lock.json package.json tests/e2e/utils.js wp-parsely.php

      - name: Update changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit changelog to trunk
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: trunk
          commit_message: Import release notes into CHANGELOG.md
          file_pattern: CHANGELOG.md
