name: Update version numbers and changelog and push them to trunk

on:
  release:
    types: [prereleased]

jobs:
  update:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.target_commitish }}
 
     # Bump version numbers and push to trunk
      - name: Update plugin version in README.md
        uses: tj-actions/sync-release-version@v11
        with:
          pattern: 'Stable tag: '
          paths: README.md
          
      - name: Update plugin version in package.json
        uses: tj-actions/sync-release-version@v11
        with:
          pattern: '"version": "'
          paths: package.json
          
      - name: Update plugin version in package-lock.json
        run: npm install

      - name: Update plugin version in tests/e2e/utils.js
        uses: tj-actions/sync-release-version@v11
        with:
          pattern: "export const PLUGIN_VERSION = '"
          paths: tests/e2e/utils.js
          
      - name: Update plugin version in wp-parsely.php - Plugin header
        uses: tj-actions/sync-release-version@v11
        with:
          pattern: ' \* Version:           '
          paths: wp-parsely.php
          
      - name: Update plugin version in wp-parsely.php - Version constant
        uses: tj-actions/sync-release-version@v11
        with:
          pattern: "const PARSELY_VERSION = '"
          paths: wp-parsely.php
            
      - name: Commit version bumps to trunk
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: trunk
          commit_message: Update plugin version to ${{ github.event.release.tag_name }}
          file_pattern: README.md package-lock.json package.json tests/e2e/utils.js wp-parsely.php

     # Update changelog and push to trunk
      - name: Update changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}
          
      - name: Update changelog 2
        run: sed -i -e "0,/$REL/ s:$REL:\[&\]:\($REL_URL\):" CHANGELOG.md
        env:
          REL: ${{ github.event.release.tag_name }}
          REL_URL: ${{ steps.update-changelog.outputs.release_compare_url }}

      - name: Commit updated changelog to trunk
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: trunk
          commit_message: Import release notes into CHANGELOG.md
          file_pattern: CHANGELOG.md
