name: Release Drafter

on:
  push:
    branches: [trunk]

permissions:
  contents: write

jobs:
  update_release_draft:
    runs-on: ubuntu-20.04
    steps:
      - name: Create a new release draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
