name: Merge trunk to develop and tag

on:
  release:
    types: [released]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
          ref: ${{ github.event.release.target_commitish }}

      - name: Merge trunk to develop branch
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: trunk
          target_branch: develop
          github_token: ${{ github.token }}
          
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ github.event.release.tag_name }}
          force_push_tag: true

#      - name: Merge trunk to ${{ github.event.release.tag_name }} tag
#        uses: devmasx/merge-branch@v1.4.0
#        with:
#          type: now
#          from_branch: trunk
#          target_branch: ${{ github.event.release.tag_name }}
#          github_token: ${{ github.token }}
