name: Update trunk changelog and merge back to develop branch

on:
  release:
    types: [released]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Update changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit changelog to trunk
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: trunk
          commit_message: Import release notes into CHANGELOG.md
          file_pattern: CHANGELOG.md

      - name: Merge trunk back to develop branch
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: trunk
          target_branch: develop
          github_token: ${{ github.token }}
