name: Update Changelog

on:
  release:
    types: [released]
    
#permissions:
#  actions: write
#  contents: write
#  packages: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v4
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          #branch: ${{ github.event.release.target_commitish }}
          branch: trunk
          commit_options: '--signoff'
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md

      - name: Merge trunk to develop
        uses: devmasx/merge-branch@v1
        with:
          type: now
          from_branch: trunk
          target_branch: develop
          github_token: ${{ github.token }}
